experiment:
  name: all_1009
  dataset_root: /media/public_dataset2/multiscan
  scenes: null
  # scene_start: scene_00005_00  # replace with first scene name (inclusive) to limit the run
  # scene_end: scene_00044_01    # replace with last scene name (inclusive) to limit the run
  # scene_start: scene_00048_00  # replace with first scene name (inclusive) to limit the run
  # scene_end: scene_00077_01    # replace with last scene name (inclusive) to limit the run
  # scene_start: scene_00086_00  # replace with first scene name (inclusive) to limit the run
  # scene_end: scene_00098_02    # replace with last scene name (inclusive) to limit the run

  scene_start: scene_00005_00  # replace with first scene name (inclusive) to limit the run
  scene_end: scene_00055_01    # replace with last scene name (inclusive) to limit the run
  # scene_start: scene_00048_00  # replace with first scene name (inclusive) to limit the run
  # scene_end: scene_00077_01    # replace with last scene name (inclusive) to limit the run
  # scene_start: scene_00058_00  # replace with first scene name (inclusive) to limit the run
  # scene_end: scene_00098_02    # replace with last scene name (inclusive) to limit the run
  levels:
    - 2
    - 4
    - 6
  tag: 246_filter_fill_prop30
  aggregate_output: false
  output_layout: scene_level
  output_root: /media/Pluto/richkung/My3DIS/outputs/experiments/{name}
stages:
  gpu: 0
  ssam:
    enabled: true
    frames:
      step: 50
    ssam_freq: 2
    min_area: 1000
    stability_threshold: 1.0
    persist_raw: true
    skip_filtering: true
    add_gaps: true
    fill_area: 10000
    append_timestamp: false
    downscale_masks: true
    downscale_ratio: 0.3
  filter:
    enabled: true
    min_area: 1000
    stability_threshold: 1.0
  tracker:
    enabled: true
    prompt_mode: all_mask
    max_propagate: 30
    iou_threshold: 0.6
    downscale_masks: true
    downscale_ratio: 0.3
    render_viz: true
  report:
    enabled: true
    name: report.md
    max_width: 640
    record_timings: true
    timing_output: stage_timings.json
