experiment:
  name: multiscan_all
  dataset_root: /media/public_dataset2/multiscan
  scenes: all
  scene_start: null  # replace with first scene name (inclusive) to limit the run
  scene_end: null    # replace with last scene name (inclusive) to limit the run
  levels:
    - 2
    - 4
    - 6
  tag: fill_prop30
  aggregate_output: true
  output_layout: scene_level
  output_root: /media/Pluto/richkung/My3DIS/outputs/experiments/{name}
stages:
  gpu: 0
  ssam:
    enabled: true
    frames:
      step: 50
    ssam_freq: 2
    min_area: 1000
    stability_threshold: 1.0
    persist_raw: false
    skip_filtering: false
    add_gaps: true
    fill_area: 10000
    append_timestamp: false
  filter:
    enabled: false
  tracker:
    enabled: true
    prompt_mode: all_mask
    max_propagate: 30
    iou_threshold: 0.6
    downscale_masks: false
    render_viz: false
  report:
    enabled: true
    name: report.md
    max_width: 640
    record_timings: true
    timing_output: stage_timings.json
